### ISSUE TITLE
Modal window not responsive

### ISSUE THREAD

**Issue by Paddy0174** [heimrichhannot/contao-fieldpalette-bundle#1]
The modal window in BE is not responsive (as the ones from contao itself).

Seems to be the width setting, that should be avoided.

Found it in two places:

src/Element/ButtonElement.php Line 206

https://github.com/heimrichhannot/contao-fieldpalette-bundle/blob/master/src/Element/ButtonElement.php#L206

src/Resources/contao/templates/fieldpalette/fieldpalette_buttons_default.html

https://github.com/heimrichhannot/contao-fieldpalette-bundle/blob/7f608a5eada48a69ccb6fee80ac7566c67a62649/src/Resources/contao/templates/fieldpalette/fieldpalette_buttons_default.html5#L2

And a second question: is there any extension, that actually uses the fieldpalette? I'd like to take a deeper look into it. Searching the code, to find how things are done, isn't a time saving way....

**Comment by fatcrobat** [comment]
Opening core modal dialog (tl_content -> module edit wizard) also opens the window in 768px width. 

Fieldpalette is used in a lot of our projects, for example https://github.com/heimrichhannot/contao-member-bundle

**Comment by Paddy0174** [comment]
Sorry, my bad, should have explained it more...

The modal window from fieldpalette doesn't change on pages that are smaller than 768px. Contaos modal window does. I made two screenshots, the first one is contao -> article ->change the settings of a module:

![fieldpalette_contao_01](https://user-images.githubusercontent.com/1948551/42159317-a1e05a5e-7df3-11e8-9936-830bca32a3df.png)

the second one is a fieldpalette in "standard" version:

![fieldpalette_fieldpalette_01](https://user-images.githubusercontent.com/1948551/42159345-b726ff6c-7df3-11e8-8241-d33132a7e2a6.png)

The modal window cannot be moved, closed or anything else, as you barely reach the buttons...

In Contao the behaviour is:
Opening modal -> resize browser window: no change (stays big)
Opening modal in already small browser window: small window
Opening modal in already small brwoser window -> resize to big: no change (stays small)

In fieldpalette it's always big, no matter if the window is called small or big, or resized afterwards.

If you look in the source of the page, contao doesn't show the width setting, if browser window was small before opening modal window. Somewhere contao seems to differantiate between browser windows an doesn't set the width in these cases.

**Comment by fatcrobat** [comment]
Thanks, should be fixed in 0.2.1.
