### ISSUE TITLE
[Bug] Drag 'n' Drop in List View Mode lädt beim Aufruf im Backend nicht

### ISSUE THREAD

**Issue by Cyrus180** [heimrichhannot/contao-fieldpalette-bundle#10]
Hallo,

die Drag 'n' Drop Funktion funktioniert im List View Mode, wenn ich das Inhaltselement im Backend zum Bearbeiten aufrufe, nicht. Sobald ich ein Element aus der Fieldpalette bearbeite oder ein neues hinzufüge, funktioniert die Drag 'n' Drop Funktion.

In der Javascript Console wird kein Fehler angezeigt.

Beim Versuch die Elemente per Drag 'n' Drop zu ziehen wird lediglich ein "n" angezeigt.
![Drag 'n' Drop](https://user-images.githubusercontent.com/4700269/75692455-e7690480-5ca5-11ea-9b0b-9bf28dc6eda3.png)

Woran könnte das liegen?

Vorab schon mal danke für eure Hilfe.

Viele Grüße

Mats

**Comment by koertho** [comment]
@Cyrus180 Hi, bitte immer mitteilen, welche Contao-Version und Bundle-Version du einsetzt :)

**Comment by Cyrus180** [comment]
Sorry, ganz vergessen.

Contao: 4.8.8
FieldPalette Bundle: 0.4.9

**Comment by koertho** [comment]
Hi, a little late reply: in my last commit I solved the issue with the cut-off titles, but sorting worked for me as expected. Maybe this is a browser specific problem, did you use Safari?
