### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by xprojects-de** [heimrichhannot/contao-fieldpalette-bundle#11]
Servus zusammen,

vorsichtige Frage: Habt ihr den Support für PHP 8 geplant und wenn ja wann? :-)

Danke und Grüße

**Comment by koertho** [comment]
@xprojects-de Hi, wir setzen PHP 8 aktuell noch nicht ein, daher ist auch nichts geplant. Du kannst das Bundle aber gerne unter 8 testen und deine Ergebnisse hier posten :)

**Comment by xprojects-de** [comment]
@koertho Servus, ok passt. Ich bin auch erst dabei meine public/private bundles so langsam fit zu machen. Aber hat noch Zeit. Ich schaue es mir gerne mal an wenn es die Zeit zulässt! :-) Danke und Grüße

**Comment by koertho** [comment]
@xprojects-de Hi, ich habe gerade PHP 8 für dieses Bundle freigegeben. Kannst gerne mal testen :)
