### ISSUE TITLE
Uncaught PHP Exception Error: "[] operator not supported for strings" at ...

### ISSUE THREAD

**Issue by ArturJo** [heimrichhannot/contao-fieldpalette-bundle#12]
Gibt es evtl. eine Lösung zu dem Fehler?
Log-Eintrag:
`[2021-04-23 09:33:18] request.CRITICAL: Uncaught PHP Exception Error: "[] operator not supported for strings" at /html/contao-fairplay-fahrergesuche/vendor/heimrichhannot/contao-fieldpalette-bundle/src/EventListener/HookListener.php line 76 {"exception":"[object] (Error(code: 0): [] operator not supported for strings at /html/contao-fairplay-fahrergesuche/vendor/heimrichhannot/contao-fieldpalette-bundle/src/EventListener/HookListener.php:76)"} []`

Meine Config: 
- PHP 7.2.10
- contao 4.9.13

**Comment by koertho** [comment]
Hi, der Fehler liegt hier wohl an einer falschen Backend-Modul-Konfiguration. Der Index `$GLOBALS['BE_MOD'][$strGroup][$strModule]['tables']` muss ein Array sein, hier scheint ein String vorzuliegen. Ohne weiteren Kontext wird es schwierig, "den Schuldigen" zu finden. Kannst du mir verraten, welches Bundle Fieldpalette nutzt?
