### ISSUE TITLE
Contao Install Tool try to delete tl_fieldpalette

### ISSUE THREAD

**Issue by luhmannAlexander** [heimrichhannot/contao-fieldpalette-bundle#14]
After update from 0.6.3 to 0.6.6. Contao Install Tool try to delete my tl_fiedlpalette.
There is my dca file that worked with 0.6.3.

[https://gist.github.com/luhmannAlexander/32d36a09c4cac4b00bc196b5b34c2685](https://gist.github.com/luhmannAlexander/32d36a09c4cac4b00bc196b5b34c2685)

search for ['fields']['cookieTools']

Do I need to change anything about it?

Thanks for any help.

**Comment by luhmannAlexander** [comment]
After update to 0.6.9 the Bug back.

**Comment by koertho** [comment]
@luhmannAlexander Could you please test if 0.6.10 fixes your problem?

**Comment by luhmannAlexander** [comment]
danke @koertho das Problem ist behoben.

Leider habe ich ein weiteres Problem. Das tritt nur bei einigen Contao Installationen auf. 
Beim Öffnen des Module kommt die Meldung "Recursion detected" 
Im Log ist folgendes zu finden.
vendor/heimrichhannot/contao-fieldpalette-bundle/src/DcaHelper/DcaHandler.php line 430 {"exception":"[object] (Error(code: 0): Recursion detected

Hab ihr vielleicht eine Idee ?

**Comment by koertho** [comment]
@luhmannAlexander Bitte ein neues Issue mit Screenshot im Dev mode dazu :) Danke!
