### ISSUE TITLE
PaletteManipulator

### ISSUE THREAD

**Issue by paddibr** [heimrichhannot/contao-fieldpalette-bundle#15]
Hi,

kann ich die fieldpalette auch mit dem PaletteManipulator hinzufügen? Ich habe Schwierigkeiten bei den fields innerhalb der fieldpalette.

**Comment by paddibr** [comment]
ich würde halt gerne den PaletteManipulator nutzen. Das habe ich für das Beispiel so gemacht:

`PaletteManipulator::create()
->addField('venues', 'account_legend', PaletteManipulator::POSITION_AFTER)
->applyToPalette('default', 'tl_member');`

Ich sehe dann die Tabelle, aber wenn ich einen neuen Datensatz anlegen möchte, bekomme ich den SQL Fehler, dass die fields innerhalb von venues nicht existieren.

**Comment by koertho** [comment]
Der Fehler hat nichts mit dem PaletteManipulator zu tun, sondern es gibt gerade ein Problem mit der Evaluation der Sub-Felder. Bin dran.

**Comment by koertho** [comment]
See #14

**Comment by paddibr** [comment]
danke! :)
