### ISSUE TITLE
Recursion detected

### ISSUE THREAD

**Issue by luhmannAlexander** [heimrichhannot/contao-fieldpalette-bundle#16]
**Context**
Contao version: 4.9
Bundle version: 0.6.11
PHP version: 7.4

**Description**
Der Fehler tritt nur bei einigen Contao Installationen auf.
Beim Öffnen des Module kommt die Meldung "Recursion detected"
Im Log ist folgendes zu finden.
vendor/heimrichhannot/contao-fieldpalette-bundle/src/DcaHelper/DcaHandler.php line 430 {"exception":"[object] (Error(code: 0): Recursion detected

Hab ihr vielleicht eine Idee ?
Vielleicht hilft auch der Inhalt der beiden Arrays

https://netzhirschde-my.sharepoint.com/personal/luhmann_netzhirsch_de/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fluhmann%5Fnetzhirsch%5Fde%2FDocuments%2FDokumente%2Fcontao%2Ehtm&parent=%2Fpersonal%2Fluhmann%5Fnetzhirsch%5Fde%2FDocuments%2FDokumente&ga=1

![grafik](https://user-images.githubusercontent.com/45062863/192479793-c70b013f-fb80-457e-bfed-3ddb47813595.png)

**Comment by koertho** [comment]
@luhmannAlexander Kannst du den Screenshot auch im Debug-Mode machen (rechts oben im Backend gibt es dazu einen Button und auch im Contao Manager irgendwo). Dann sind die Fehlermeldungen ausführlicher :)

Auf die Sharepoint-Daten haben ich leider keinen Zugriff.

**Comment by luhmannAlexander** [comment]
Geht leider nicht. Dann kommt eine andere Fehlermeldung 
![grafik](https://user-images.githubusercontent.com/45062863/192488441-acdb9974-33a2-45e6-9328-331d92ee31a7.png)

Ich habe die Arrays einmal mit var_dump ausgeben. Zuerst das defaults dann custom
![grafik](https://user-images.githubusercontent.com/45062863/192488376-96780cad-54b7-4cf7-b904-04a33ec7f970.png)

**Comment by koertho** [comment]
Klassisches PHP8-Problem :D
Kein Problem, ich schau mal, ob ich den Bug beheben kann.

**Comment by luhmannAlexander** [comment]
Hi ich konnte das Problem jetzt lokal nachstellen. Nun kommt es aber beim Erstellen eine neuen Fieldpalettes bzw. wenn das zum Erstellen Fenster aufgerufen wird.

Kann ich dir noch irgendwelche Detail liefern? Wenn du im Contao-Manger das "Netzhirsch Cookie Opt In Bundle" installierst und ein Module vom Type "Cookie Opt in Bar" erstellst kommt der Fehler. Vielleicht erst beim anlegen eines Tools "Neues Element"

![Screenshot 2022-10-05 at 09-43-41 Themes test Frontend-Module Modul ID 2 bearbeiten clear-contao localhost](https://user-images.githubusercontent.com/45062863/194007498-02788e94-b7d2-4577-a686-5fda4d23fe87.png)

**Comment by koertho** [comment]
Sorry, bin leider noch nicht dazu gekommen. Eventuell könntest du es mit einer älteren Version probieren.

**Comment by koertho** [comment]
@luhmannAlexander Kannst du bitte testen, ob #17 das Problem für die behebt? Bei mir hat es funktionert, bekomme aber im Anschluss ein Fehler durch euren Code ;)

**Comment by luhmannAlexander** [comment]
Hat leider nicht funktioniert. Es liegt eindeutlich an den label mit "&". Ich habe jetzt ersmal einfach die Übersetzung direkt rein geschrieben. Somit funktioniert es nur noch in einer Sprache, was aber kein Problem ist.

**Comment by luhmannAlexander** [comment]
z.B.
$GLOBALS['TL_DCA']['tl_module']['fields']['cookieTools']['fieldpalette']['fields']['cookieToolsName']['label'] = &$GLOBALS['TL_LANG']['tl_module']['cookieToolsName']

Soweit ich das verstanden haben. Kann man damit Übersetzungen umsetzen.

**Comment by paddibr** [comment]
nach der Umstellung von PHP 7.4 auf PHP 8.0 habe ich auch den Fehler beim "Neu erstellen".

**Comment by koertho** [comment]
@paddibr Hast du schon mit #17 getestet? Kannst du deine Feld-Definition hier angeben?

**Comment by paddibr** [comment]
@koertho danke, mit dem branch funktioniert es. Braucht ihr trotzdem noch die Feld-Definition?
Könnt ihr das mit in den Master mergen? :)
