### ISSUE TITLE
Contao 5

### ISSUE THREAD

**Issue by luhmannAlexander** [heimrichhannot/contao-fieldpalette-bundle#18]
Hi, gibt es schon eine Planung, ob das Bundle für Contao 5 angepasst wird.

**Comment by koertho** [comment]
Hallo, wir planen das nicht für einzelne Erweiterungen. Wenn wir Contao 5 einsetzen, passiert dies dann automatisch. Da wir nur LTS-Versionen einsetzen, wird es sicher noch etwas dauern. Du darfst es gerne testen und PRs anbieten, wenn du magst :)
Alternativ könntest du dir auch mal das group-widget von Moritz anschauen (<https://github.com/m-vo/contao-group-widget>), dass ist schon Contao 5 ready.

**Comment by luhmannAlexander** [comment]
Danke für den Hinweis.
