### ISSUE TITLE
Twig error in fieldpalette_list_default.html.twig

### ISSUE THREAD

**Issue by Paddy0174** [heimrichhannot/contao-fieldpalette-bundle#2]
This is the error I'm getting:

`[2018-07-12 14:27:14] app.CRITICAL: An exception occurred. {"exception":"[object] (Twig_Error_Syntax(code: 0): Unexpected token \"end of statement block\" of value \"\". at /var/www/virtual/*snip*/vendor/heimrichhannot/contao-fieldpalette-bundle/src/Resources/views/list/fieldpalette_list_default.html.twig:17)"} []`

In the template, there is an "elseif" where there should be just an "else".

https://github.com/heimrichhannot/contao-fieldpalette-bundle/blob/master/src/Resources/views/list/fieldpalette_list_default.html.twig#L17

I'm sorry, it seems, I cannot post a PR or even a second code snippet in this post... Strange...

PS: Thanks for solving the last error so fast! :)

**Comment by koertho** [comment]
Thanks for reporting this. Solved in 5f6697b, will be released as soon as tests finished.
