### ISSUE TITLE
Wie erweitere ich bestehende Tabellen?

### ISSUE THREAD

**Issue by dabasti** [heimrichhannot/contao-fieldpalette-bundle#6]
Hallo,

leider bietet mir die Dokumentation nicht wirklich genug Informationen um einfach starten zu können.
Wo müssen genannte Codebeispiele verwendet werden um passende Ergebnisse zu bekommen?

Vielen Dank.

**Comment by koertho** [comment]
Was für Ergebnisse sollen denn erreicht werden?
Es wurde immer am Beginn der Beispiele die Datei genannt, aus welcher das Beispiel stammt.

**Comment by dabasti** [comment]
Ich möchte zum Beispiel ein neues Feld zu tl_news hinzufügen, wie es früher über die dcaconfig möglich war

**Comment by koertho** [comment]
Ich habe nie mit der dcaconfig gearbeitet, daher wei ich nicht, was diese für möglichkeiten bietet. Das FieldPalette-Bundle ist praktisch gesehen ein DCA-Input-Type, kein DCA-Ersatz.

**Comment by dabasti** [comment]
Verstehe. Aber zurück zur Frage. Wie / Wo ist es mir möglich neue Felder für bestehende Tabellen zu definieren?

In der Dokumentation werden zwar codebeispiele genannt, allerdings wird nirgends gesagt welche Dateien erstellt / bearbeitet werden müssen.

**Comment by koertho** [comment]
Du kannst ein FieldPalette-Feld einfach wie jedes andere DCA-Feld in deiner DCA-Konfiuration definieren. Ist eigentlich klar dokumentiert. Nimm deine `tl_*.php` Datei und füge ein neues Feld vom Typ `fieldpalette` hinzu. Kopiere dir am besten den Code des `venues`-Feld aus dem ersten Beispiel und passe diesen an. Danach Datenbank aktualisieren, fertig.

**Comment by dabasti** [comment]
Welche `tl_*.php` Datei ist denn gemeint? Muss erst ein Bundle erstellt werden?
